/**
 * Mock catalogue. Stands in for the platform's course/project/assessment
 * inventory plus a skill taxonomy.
 *
 * Everything here is data, not logic — swapping in a real catalogue means
 * replacing this file (or fetching into the same shapes) and nothing else.
 */

import type { Resource, Skill, SkillId } from './types'

export const SKILLS: Skill[] = [
  // foundations
  { id: 'python', name: 'Python', domain: 'foundations' },
  { id: 'stats', name: 'Statistics', domain: 'foundations' },
  { id: 'linalg', name: 'Linear Algebra', domain: 'foundations' },
  { id: 'sql', name: 'SQL', domain: 'foundations' },
  { id: 'git', name: 'Version Control', domain: 'foundations' },

  // data
  { id: 'wrangling', name: 'Data Wrangling', domain: 'data' },
  { id: 'viz', name: 'Data Visualisation', domain: 'data' },
  { id: 'ml', name: 'ML Fundamentals', domain: 'data' },
  { id: 'deep-learning', name: 'Deep Learning', domain: 'data' },
  { id: 'nlp', name: 'NLP', domain: 'data' },
  { id: 'experiments', name: 'Experiment Design', domain: 'data' },
  { id: 'mlops', name: 'MLOps', domain: 'data' },

  // engineering
  { id: 'html-css', name: 'HTML & CSS', domain: 'engineering' },
  { id: 'javascript', name: 'JavaScript', domain: 'engineering' },
  { id: 'typescript', name: 'TypeScript', domain: 'engineering' },
  { id: 'react', name: 'React', domain: 'engineering' },
  { id: 'node', name: 'Node.js', domain: 'engineering' },
  { id: 'api-design', name: 'API Design', domain: 'engineering' },
  { id: 'testing', name: 'Testing', domain: 'engineering' },
  { id: 'system-design', name: 'System Design', domain: 'engineering' },

  // infrastructure
  { id: 'linux', name: 'Linux', domain: 'infrastructure' },
  { id: 'docker', name: 'Containers', domain: 'infrastructure' },
  { id: 'k8s', name: 'Kubernetes', domain: 'infrastructure' },
  { id: 'ci-cd', name: 'CI/CD', domain: 'infrastructure' },
  { id: 'cloud', name: 'Cloud Platforms', domain: 'infrastructure' },
  { id: 'iac', name: 'Infrastructure as Code', domain: 'infrastructure' },
  { id: 'observability', name: 'Observability', domain: 'infrastructure' },
]

export const SKILL_BY_ID: Record<SkillId, Skill> = Object.fromEntries(
  SKILLS.map((s) => [s.id, s]),
)

export function skillName(id: SkillId): string {
  return SKILL_BY_ID[id]?.name ?? id
}

export const RESOURCES: Resource[] = [
  // ---------------- foundations ----------------
  {
    id: 'py-basics',
    title: 'Python Foundations',
    kind: 'course',
    provider: 'OpenCampus',
    hours: 18,
    level: 1,
    teaches: { python: 3 },
    summary: 'Syntax, data structures, functions and file handling, with weekly exercises.',
    tags: ['programming', 'beginner'],
  },
  {
    id: 'py-data',
    title: 'Python for Data Analysis',
    kind: 'course',
    provider: 'DataForge',
    hours: 22,
    level: 2,
    teaches: { python: 4, wrangling: 3 },
    requires: { python: 2 },
    summary: 'pandas and NumPy for real datasets: reshaping, joins, missing data, time series.',
    tags: ['data', 'analytics'],
  },
  {
    id: 'stats-inference',
    title: 'Statistical Inference',
    kind: 'course',
    provider: 'Northline University',
    hours: 26,
    level: 2,
    teaches: { stats: 3, experiments: 2 },
    summary: 'Distributions, estimation, hypothesis testing and confidence intervals.',
    tags: ['maths', 'analytics'],
  },
  {
    id: 'linalg-ml',
    title: 'Linear Algebra for Machine Learning',
    kind: 'course',
    provider: 'Northline University',
    hours: 20,
    level: 2,
    teaches: { linalg: 3 },
    summary: 'Vectors, matrices, decompositions and the geometry behind model training.',
    tags: ['maths'],
  },
  {
    id: 'sql-essentials',
    title: 'SQL Essentials',
    kind: 'course',
    provider: 'DataForge',
    hours: 12,
    level: 1,
    teaches: { sql: 3 },
    summary: 'Querying, joins, aggregation and window functions against a sample warehouse.',
    tags: ['data', 'databases'],
  },
  {
    id: 'git-workflow',
    title: 'Version Control with Git',
    kind: 'course',
    provider: 'OpenCampus',
    hours: 8,
    level: 1,
    teaches: { git: 3 },
    summary: 'Branching, merging, rebasing and reviewing changes in a team workflow.',
    tags: ['tooling'],
  },

  // ---------------- data / ML ----------------
  {
    id: 'ml-foundations',
    title: 'Machine Learning Foundations',
    kind: 'course',
    provider: 'Northline University',
    hours: 34,
    level: 2,
    teaches: { ml: 3, stats: 3 },
    requires: { python: 3, stats: 2, linalg: 2 },
    summary: 'Regression, classification, regularisation, cross-validation and model selection.',
    tags: ['machine learning', 'ai'],
  },
  {
    id: 'ml-project-churn',
    title: 'Project: Customer Churn Predictor',
    kind: 'project',
    provider: 'Guided Build',
    hours: 14,
    level: 2,
    teaches: { ml: 4, wrangling: 4, python: 4 },
    requires: { ml: 3, python: 3 },
    summary: 'Build, evaluate and defend a churn model end to end on a messy real dataset.',
    tags: ['machine learning', 'portfolio'],
  },
  {
    id: 'dl-specialisation',
    title: 'Deep Learning Specialisation',
    kind: 'course',
    provider: 'Northline University',
    hours: 46,
    level: 3,
    teaches: { 'deep-learning': 4, ml: 4 },
    requires: { ml: 3, linalg: 3, python: 3 },
    summary: 'Neural networks from scratch through CNNs, sequence models and training strategy.',
    tags: ['deep learning', 'ai', 'computer vision'],
  },
  {
    id: 'nlp-transformers',
    title: 'NLP with Transformers',
    kind: 'course',
    provider: 'DataForge',
    hours: 28,
    level: 3,
    teaches: { nlp: 4, 'deep-learning': 4 },
    requires: { 'deep-learning': 3, python: 3 },
    summary: 'Tokenisation, attention, fine-tuning and evaluation of transformer models.',
    tags: ['nlp', 'llm', 'ai'],
  },
  {
    id: 'nlp-project-support',
    title: 'Project: Support Ticket Classifier',
    kind: 'project',
    provider: 'Guided Build',
    hours: 16,
    level: 3,
    teaches: { nlp: 4, mlops: 2 },
    requires: { nlp: 3 },
    summary: 'Fine-tune and ship a multi-label text classifier with a served inference endpoint.',
    tags: ['nlp', 'portfolio'],
  },
  {
    id: 'mlops-production',
    title: 'ML in Production',
    kind: 'course',
    provider: 'CloudPath',
    hours: 24,
    level: 3,
    teaches: { mlops: 4, docker: 3, 'ci-cd': 3 },
    requires: { ml: 3, python: 3 },
    summary: 'Packaging, serving, monitoring, drift detection and retraining pipelines.',
    tags: ['mlops', 'deployment'],
  },
  {
    id: 'ab-testing',
    title: 'Experiment Design & A/B Testing',
    kind: 'course',
    provider: 'DataForge',
    hours: 16,
    level: 2,
    teaches: { experiments: 4, stats: 4 },
    requires: { stats: 3 },
    summary: 'Power analysis, randomisation, guardrail metrics and reading results honestly.',
    tags: ['analytics', 'product'],
  },
  {
    id: 'viz-storytelling',
    title: 'Data Visualisation & Storytelling',
    kind: 'course',
    provider: 'OpenCampus',
    hours: 14,
    level: 2,
    teaches: { viz: 4 },
    requires: { python: 2 },
    summary: 'Choosing encodings, designing for an audience and building dashboards that hold up.',
    tags: ['data', 'communication', 'design'],
  },
  {
    id: 'analyst-capstone',
    title: 'Project: Revenue Analytics Dashboard',
    kind: 'project',
    provider: 'Guided Build',
    hours: 18,
    level: 2,
    teaches: { viz: 4, sql: 4, wrangling: 4 },
    requires: { sql: 3, viz: 3 },
    summary: 'Model a warehouse, build the metrics layer and ship a dashboard stakeholders use.',
    tags: ['analytics', 'portfolio'],
  },
  {
    id: 'assess-ml',
    title: 'Assessment: ML Fundamentals',
    kind: 'assessment',
    provider: 'Pathfinder',
    hours: 2,
    level: 2,
    teaches: {},
    requires: { ml: 3 },
    summary: 'Timed evaluation covering model selection, evaluation metrics and leakage traps.',
    tags: ['assessment'],
  },
  {
    id: 'assess-sql',
    title: 'Assessment: SQL Proficiency',
    kind: 'assessment',
    provider: 'Pathfinder',
    hours: 1,
    level: 1,
    teaches: {},
    requires: { sql: 3 },
    summary: 'Query-writing challenge scored on correctness and efficiency.',
    tags: ['assessment'],
  },

  // ---------------- web engineering ----------------
  {
    id: 'web-foundations',
    title: 'Modern HTML & CSS',
    kind: 'course',
    provider: 'OpenCampus',
    hours: 16,
    level: 1,
    teaches: { 'html-css': 3 },
    summary: 'Semantic markup, flexbox, grid and responsive layout without a framework.',
    tags: ['web', 'frontend', 'design'],
  },
  {
    id: 'js-deep',
    title: 'JavaScript in Depth',
    kind: 'course',
    provider: 'OpenCampus',
    hours: 24,
    level: 2,
    teaches: { javascript: 4 },
    requires: { 'html-css': 2 },
    summary: 'Closures, prototypes, async, modules and the browser event loop.',
    tags: ['web', 'frontend'],
  },
  {
    id: 'ts-systems',
    title: 'TypeScript for Large Codebases',
    kind: 'course',
    provider: 'DataForge',
    hours: 14,
    level: 2,
    teaches: { typescript: 4 },
    requires: { javascript: 3 },
    summary: 'Generics, narrowing, structural typing and modelling domains with types.',
    tags: ['web', 'types'],
  },
  {
    id: 'react-patterns',
    title: 'React Patterns & Performance',
    kind: 'course',
    provider: 'OpenCampus',
    hours: 26,
    level: 2,
    teaches: { react: 4, javascript: 4 },
    requires: { javascript: 3 },
    summary: 'Composition, state management, data fetching and render performance.',
    tags: ['web', 'frontend', 'react'],
  },
  {
    id: 'node-services',
    title: 'Backend Services with Node',
    kind: 'course',
    provider: 'CloudPath',
    hours: 22,
    level: 2,
    teaches: { node: 4, 'api-design': 3 },
    requires: { javascript: 3 },
    summary: 'HTTP servers, middleware, persistence, background jobs and error handling.',
    tags: ['web', 'backend'],
  },
  {
    id: 'api-rest',
    title: 'API Design & Authentication',
    kind: 'course',
    provider: 'CloudPath',
    hours: 16,
    level: 2,
    teaches: { 'api-design': 4 },
    requires: { 'api-design': 2 },
    summary: 'Resource modelling, versioning, pagination, OAuth and session security.',
    tags: ['backend', 'security'],
  },
  {
    id: 'testing-web',
    title: 'Testing Web Applications',
    kind: 'course',
    provider: 'OpenCampus',
    hours: 12,
    level: 2,
    teaches: { testing: 4 },
    requires: { javascript: 3 },
    summary: 'Unit, integration and end-to-end testing, plus what not to test.',
    tags: ['web', 'quality'],
  },
  {
    id: 'fullstack-capstone',
    title: 'Project: Full-Stack Booking Platform',
    kind: 'project',
    provider: 'Guided Build',
    hours: 30,
    level: 3,
    teaches: { react: 4, node: 4, 'api-design': 4, testing: 3 },
    requires: { react: 3, node: 3 },
    summary: 'Ship an authenticated multi-tenant app with payments, tests and a deploy pipeline.',
    tags: ['web', 'portfolio'],
  },
  {
    id: 'system-design-core',
    title: 'System Design Fundamentals',
    kind: 'course',
    provider: 'Northline University',
    hours: 20,
    level: 3,
    teaches: { 'system-design': 4 },
    requires: { 'api-design': 3 },
    summary: 'Caching, queues, replication, consistency trade-offs and capacity estimation.',
    tags: ['architecture', 'interview'],
  },
  {
    id: 'assess-react',
    title: 'Assessment: React Component Challenge',
    kind: 'assessment',
    provider: 'Pathfinder',
    hours: 3,
    level: 2,
    teaches: {},
    requires: { react: 3 },
    summary: 'Timed build of an accessible, state-heavy component reviewed against a rubric.',
    tags: ['assessment'],
  },

  // ---------------- infrastructure ----------------
  {
    id: 'linux-cli',
    title: 'Linux & the Command Line',
    kind: 'course',
    provider: 'CloudPath',
    hours: 14,
    level: 1,
    teaches: { linux: 3 },
    summary: 'Filesystems, processes, permissions, networking basics and shell scripting.',
    tags: ['infrastructure', 'tooling'],
  },
  {
    id: 'docker-fundamentals',
    title: 'Containers with Docker',
    kind: 'course',
    provider: 'CloudPath',
    hours: 14,
    level: 2,
    teaches: { docker: 4 },
    requires: { linux: 2 },
    summary: 'Images, layers, volumes, networking and writing production-grade Dockerfiles.',
    tags: ['infrastructure', 'devops'],
  },
  {
    id: 'k8s-operations',
    title: 'Kubernetes in Practice',
    kind: 'course',
    provider: 'CloudPath',
    hours: 30,
    level: 3,
    teaches: { k8s: 4 },
    requires: { docker: 3, linux: 3 },
    summary: 'Workloads, services, config, autoscaling and debugging a live cluster.',
    tags: ['infrastructure', 'devops'],
  },
  {
    id: 'cicd-pipelines',
    title: 'CI/CD Pipelines',
    kind: 'course',
    provider: 'CloudPath',
    hours: 12,
    level: 2,
    teaches: { 'ci-cd': 4 },
    requires: { git: 3 },
    summary: 'Build, test and deploy automation with environments, gates and rollbacks.',
    tags: ['devops', 'automation'],
  },
  {
    id: 'cloud-aws-core',
    title: 'Cloud Platform Core Services',
    kind: 'course',
    provider: 'CloudPath',
    hours: 26,
    level: 2,
    teaches: { cloud: 4, observability: 2 },
    requires: { linux: 2 },
    summary: 'Compute, storage, networking, IAM and cost control on a major cloud.',
    tags: ['cloud', 'infrastructure'],
  },
  {
    id: 'terraform-iac',
    title: 'Infrastructure as Code',
    kind: 'course',
    provider: 'CloudPath',
    hours: 18,
    level: 3,
    teaches: { iac: 4 },
    requires: { cloud: 3 },
    summary: 'Declarative provisioning, state management, modules and safe change review.',
    tags: ['devops', 'cloud'],
  },
  {
    id: 'observability-course',
    title: 'Observability & Incident Response',
    kind: 'course',
    provider: 'CloudPath',
    hours: 16,
    level: 3,
    teaches: { observability: 4 },
    requires: { cloud: 2 },
    summary: 'Metrics, logs, traces, alerting that does not cry wolf, and running an incident.',
    tags: ['devops', 'reliability'],
  },
  {
    id: 'devops-capstone',
    title: 'Project: Zero-Downtime Deployment Platform',
    kind: 'project',
    provider: 'Guided Build',
    hours: 24,
    level: 3,
    teaches: { k8s: 4, 'ci-cd': 4, iac: 4, observability: 3 },
    requires: { k8s: 3, 'ci-cd': 3 },
    summary: 'Provision, deploy and observe a service with blue/green releases and rollback drills.',
    tags: ['devops', 'portfolio'],
  },
]

export const RESOURCE_BY_ID: Record<string, Resource> = Object.fromEntries(
  RESOURCES.map((r) => [r.id, r]),
)

export function getResource(id: string): Resource | undefined {
  return RESOURCE_BY_ID[id]
}

/** Interest tags offered in the profile editor. Derived from the catalogue. */
export const ALL_TAGS: string[] = Array.from(
  new Set(RESOURCES.flatMap((r) => r.tags ?? [])),
).sort()
